// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8IiFdlFRkBsnjDyFZY3xCFZLMe9ksIN0',
    appId: '1:660104539628:web:f489a7b911b1d889aa64c9',
    messagingSenderId: '660104539628',
    projectId: 'disha-8804e',
    authDomain: 'disha-8804e.firebaseapp.com',
    storageBucket: 'disha-8804e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgawYRJYSA5pNwt0L7BiiUQhCy3eRfsHc',
    appId: '1:660104539628:android:6c15cdfb36c9970baa64c9',
    messagingSenderId: '660104539628',
    projectId: 'disha-8804e',
    storageBucket: 'disha-8804e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtxT3_2kWjLpB3UT6T8ojdcfotI1a6wlg',
    appId: '1:660104539628:ios:78bb61ad5e2ee3f9aa64c9',
    messagingSenderId: '660104539628',
    projectId: 'disha-8804e',
    storageBucket: 'disha-8804e.appspot.com',
    iosClientId: '660104539628-fjgppr447pgfvfmj8sghqn04crt38dcq.apps.googleusercontent.com',
    iosBundleId: 'com.example.disha',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtxT3_2kWjLpB3UT6T8ojdcfotI1a6wlg',
    appId: '1:660104539628:ios:78bb61ad5e2ee3f9aa64c9',
    messagingSenderId: '660104539628',
    projectId: 'disha-8804e',
    storageBucket: 'disha-8804e.appspot.com',
    iosClientId: '660104539628-fjgppr447pgfvfmj8sghqn04crt38dcq.apps.googleusercontent.com',
    iosBundleId: 'com.example.disha',
  );
}
